export * from './interface/common'
export * from './interface/axios-types'
export * from './interface/store'

export * from './interface/else'
export * from './interface/home'
export * from './interface/activity'
export * from './interface/coupon'
export * from './interface/promotion'
export * from './interface/user'
export * from './interface/gameList'
export * from './interface/dailyProfitRank'
export * from './interface/swiper'
export * from './interface/wallet'
export * from './interface/vip'
